name: Create issue test

on:
  workflow_dispatch:
    inputs:
      ISSUE_TEXT:
        description: 'Issue text'
        type: string
        required: true
        default: 'us10'
  workflow_call:
    inputs:
      ISSUE_TEXT:
        description: 'Issue text'
        type: string
        required: true
        default: 'us10'
 
jobs:
  execute_infra_setup:
    name: Test GH issues
    runs-on: ubuntu-latest

    steps:

    - name: Check out Git repository
      id: checkout_repo
      uses: actions/checkout@v4


    # - uses: actions/github-script@v7
    #   with:
    #     script: |
    #         github.rest.issues.create({
    #             issue_number: context.issue.number,
    #             owner: context.repo.owner,
    #             repo: context.repo.repo,
    #             labels: ['Triage']
    #         })

    # create an issue with the provided text
    - name: Create issue
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Test issue',
            body: "${{ github.event.inputs.ISSUE_TEXT }}"
          })