name: Trigger deployments for target regions

on:
  workflow_dispatch:

jobs:
  RegionDeploymentMatrix:
    strategy:
      matrix:
        region: ['us10']
    uses: 'demosbtp/eab-2024-04/.github/workflows/deploy_infra.yml@wf-setup'
    with:
      REGION: ${{ matrix.region }}
    secrets:
      BTP_USERNAME: ${{ secrets.BTP_USERNAME }}
      BTP_PASSWORD: ${{ secrets.BTP_PASSWORD }}
      GLOBALACCOUNT: ${{ secrets.GLOBALACCOUNT }}
    