name: Trigger deployments for target regions

on:
  workflow_dispatch:

jobs:
  RegionDeploymentMatrix:
    strategy:
      matrix:
        region: ['us10', 'eu10', 'ap10']
    uses: './.github/workflows/deploy_infra.yml'
    with:
      REGION: ${{ matrix.region }}
    secrets: inherit
    