name: Trigger deployments for target regions

on:
  workflow_dispatch:

jobs:
  RegionDeploymentMatrix:
    strategy:
      matrix:
        region: ['us10']
    uses: 'demosbtp/eab-2024-04/.github/workflows/deploy_infra.yml@main'
    with:
      REGION: ${{ matrix.region }}
    secrets: inherit
    