name: Run CF commands

on:
  workflow_dispatch:


jobs:
  execute_infra_setup:
    name: Project Setup
    runs-on: ubuntu-latest
    steps:

    - name: Check out Git repository
      id: checkout_repo
      uses: actions/checkout@v4
      
    - name: Assign CF users
      id: assign_cf_users
      uses: ./.github/actions/sap-btp-cf
      with:
        cf_api: https://api.cf.us10.hana.ondemand.com
        cf_username: ${{ secrets.BTP_USERNAME }}
        cf_password: ${{ secrets.BTP_PASSWORD }}
        cf_org: eab-2024-04
        cf_space: dev
        command: |
          cf8 set-org-role rui.nogueira@sap.com eab-2024-04 OrgManager \
          && cf8 set-org-role christian.lechner@sap.com eab-2024-04 OrgManager --origin sap.default\
          && cf8 set-space-role rui.nogueira@sap.com eab-2024-04 dev SpaceManager \
          && cf8 set-space-role rui.nogueira@sap.com eab-2024-04 dev SpaceDeveloper \
          && cf8 set-space-role christian.lechner@sap.com eab-2024-04 dev SpaceManager  --origin sap.default\
          && cf8 set-space-role christian.lechner@sap.com eab-2024-04 dev SpaceDeveloper  --origin sap.default

    - name: Deploy MTAR
      id: deploy_mtar
      uses: ./.github/actions/sap-btp-cf
      with:
        cf_api: https://api.cf.us10.hana.ondemand.com
        cf_username: ${{ secrets.BTP_USERNAME }}
        cf_password: ${{ secrets.BTP_PASSWORD }}
        cf_org: eab-2024-04
        cf_space: dev
        command: |
          deploy ./src/gen/cap-app.mtar -f