name: Trigger deployments for target regions

on:
  workflow_dispatch:

jobs:
  RegionDeploymentMatrix:
    strategy:
      matrix:
        region: ['us10']
    uses: ./.github/workflows/deploy_infra.yml
    with:
      region: ${{ matrix.region }}
    secrets:
      BTP_USERNAME: ${{ secrets.BTP_USERNAME }}
      BTP_PASSWORD: ${{ secrets.BTP_PASSWORD }}
      GLOBALACCOUNT: ${{ secrets.GLOBALACCOUNT }}
    