name: Trigger deployments for target regions

on:
  workflow_dispatch:

jobs:
  RegionDeploymentMatrix:
    strategy:
      fail-fast: false
      matrix:
        # region: ['us10', 'eu10', 'ap10']
        region: ['ap10', 'ap11', "ap12", "ap20", "ap21", "br10", "ca10", "eu10", "eu11", "eu20", "jp10", "jp20", "us10", "us20", "us21", "us30", "eu30", "in30", "ch20", "sa30", "jp30"]
    uses: './.github/workflows/deploy_infra.yml'
    with:
      REGION: ${{ matrix.region }}
    secrets: inherit
    
       