name: Fetch the list of HTML5 apps in an SAP subaccount

on:
  workflow_dispatch:

  workflow_call:

jobs:
  execute_infra_setup:
    name: Project Setup
    runs-on: ubuntu-latest
    env: 
      CF_ORG_ID: ''
      CF_ORG_NAME: 'eab-2024-04'
      CF_API_URL: 'https://api.cf.us10.hana.ondemand.com'
      CF_SPACE_NAME: 'dev'
      CF_SPACE_ID: ''
    steps:

    - name: Check out Git repository
      id: checkout_repo
      uses: actions/checkout@v4
     

    - name: Fetch app URL
      id: fetch_app_url
      uses: ./.github/actions/sap-btp-cf
      with:
        cf_api: ${{ env.CF_API_URL }}
        cf_username: ${{ secrets.BTP_USERNAME }}
        cf_password: ${{ secrets.BTP_PASSWORD }}
        cf_org: ${{ env.CF_ORG_NAME }}
        cf_space: ${{ env.CF_SPACE_NAME }}
        command: |
          cf8 install-plugin -r CF-Community "html5-plugin" -f \
          # Fetch the list of HTML5 apps in the subaccount and only give back the one that has Launchpad in the name
          APP_URL_OUTPUT=$(cf html5-list -d -u | grep -Eo '(http|https)://[a-zA-Z0-9./?=_%:-]*' | grep -Eo '.*Launchpad.*' | sed -e "s/.cpp./.launchpad./g")"
          echo "APP_URL_OUTPUT=$APP_URL_OUTPUT" >> $GITHUB_ENV
          



